inventory= [
    {
        productID: 1,
        warehouseID: '1jhdsfkjhskjdh',
        name: 'Socks',
        description: 'Premium socks made from Russian elk fur',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 2,
        warehouseID: '2jhdsfkjhskjdh',
        name: 'Shoes',
        description: 'Nike high tops with a solid gold swoosh, because money',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 3,
        warehouseID: '3jhdsfkjhskjdh',
        name: 'Pants',
        description: 'Sweet ass cargo pants with enough pockets for all your drugs',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 4,
        warehouseID: '4jhdsfkjhskjdh',
        name: 'Shirt',
        description: 'Gucci, its all Gucci',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 5,
        warehouseID: '5jhdsfkjhskjdh',
        name: 'Hat',
        description: 'Snap back, for when you go bald',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 6,
        warehouseID: '6jhdsfkjhskjdh',
        name: 'Sweater',
        description: 'Pre-stained baggy sweater for that "im still drunk" look',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 7,
        warehouseID: '7jhdsfkjhskjdh',
        name: 'Spanx',
        description: 'Look skinny in secconds! May cause organ displacement',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
    {
        productID: 8,
        warehouseID: '8jhdsfkjhskjdh',
        name: 'bandana',
        description: 'Were all gansters at heart',
        lastOrdered: '05/24/2018',
        orderedBy: 'Jim Bob',
        referenceNo: 'jhdsfhk76832738223',
        productCategory: 'Automotive',
        quantity: 2000,
        location: 'Toronto, ON',
        status: 'in stock'
    },
]
